steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "northamerica-northeast2-docker.pkg.dev/protean-music-371922/hariprasath-100889196/appimg:$COMMIT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "northamerica-northeast2-docker.pkg.dev/protean-music-371922/hariprasath-100889196/appimg:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args: ["run", "deploy", "cloud-build", "--image", "northamerica-northeast2-docker.pkg.dev/protean-music-371922/hariprasath-100889196/appimg:$COMMIT_SHA", "--platform", "managed", "--region", "us-central1", "--allow-unauthenticated", "--concurrency", "1"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
    - 'source'
    - 'repos'
    - 'files'
    - 'update'
    - 'index.html'
    - '--message'
    - 'Update index.html title to Assignment 2 - 100889196'
    - '--content'
    - 'src/static/index.html=Assignment 2 - 100889196'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
    - 'source'
    - 'repos'
    - 'update'
    - '--add'
    - 'index.html'
    - '--message'
    - 'Update index.html title to Assignment 2 - 100889196'
    - '--content'
    - 'src/static/index.html'
timeout: 600s
substitutions:
  _COMMIT_SHA: ${_GITHUB_SHA}
options:
  substitution_option: ALLOW_LOOSE
  logging: GCS_ONLY
  machineType: N1_HIGHCPU_8
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
