steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/scenic-doodad-401715/hariprasath-100889196:${COMMIT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/scenic-doodad-401715/hariprasath-100889196:${COMMIT_SHA}']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'your-service-name'
      - '--image=us-central1-docker.pkg.dev/scenic-doodad-401715/hariprasath-100889196:${COMMIT_SHA}'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
