steps:
  # Build the Docker image kevin
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/devops-414603/hariprasath-100889196/appimg:${COMMIT_SHA}', '.']
  # Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/devops-414603/hariprasath-100889196/appimg:${COMMIT_SHA}']
  
