steps:
#use your artifact registry as the name and tag it with the commit SHA
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "northamerica-northeast1-docker.pkg.dev/devops-414603/hariprasath-100889196/appimg:$COMMIT_SHA", "."]
#Push the image to your artifact registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "northamerica-northeast1-docker.pkg.dev/devops-414603/hariprasath-100889196/appimg:$COMMIT_SHA"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      gcloud run deploy nodejs-app \
        --image=northamerica-northeast1-docker.pkg.dev/devops-414603/hariprasath-100889196/appimg:${_COMMIT_SHA} \
        --platform=managed \
        --region=us-central1 \
        --port=3000 \
        --allow-unauthenticated
timeout: 600s
substitutions:
  _COMMIT_SHA: ${_GITHUB_SHA}
options:
  substitution_option: ALLOW_LOOSE
  logging: GCS_ONLY
  machineType: E2_HIGHCPU_2
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
images:
  # Define the images to store in Google Artifact Registry
  - northamerica-northeast1-docker.pkg.dev/devops-414603/hariprasath-100889196/appimg:${_COMMIT_SHA}
