steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "northamerica-northeast2-docker.pkg.dev/protean-music-371922/hariprasath-100889196/appimg:$COMMIT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "northamerica-northeast2-docker.pkg.dev/protean-music-371922/hariprasath-100889196/appimg:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args: ["run", "deploy", "cloud-build", "--image", "northamerica-northeast2-docker.pkg.dev/protean-music-371922/hariprasath-100889196/appimg:$COMMIT_SHA", "--platform", "managed", "--region", "us-central1", "--allow-unauthenticated", "--concurrency", "1"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args: ["config", "set", "project", "YOUR_PROJECT_ID"]
- name: 'Copy updated file to Cloud Storage'
  entrypoint: 'gsutil'
  args: ["cp", "-r", "src/static/*", "gs://YOUR_BUCKET/src/static/"]
#  OR
# - name: 'Deploy function with updated file'
#   entrypoint: 'gcloud'
#   args: ["functions", "deploy", "YOUR_FUNCTION_NAME", "--runtime", "YOUR_RUNTIME", "--allow-unauthenticated", "--trigger-http", "--set-env-vars", "SERVICE_ACCOUNT=YOUR_SERVICE_ACCOUNT", "--source", "."]
timeout: 600s
substitutions:
  _COMMIT_SHA: ${_GITHUB_SHA}
options:
  substitution_option: ALLOW_LOOSE
  logging: GCS_ONLY
  machineType: N1_HIGHCPU_8
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
